services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - '${KEYCLOAK_PORT}:8080'
    env_file: .env
    # Starting in development mode which enables on-the-fly theme updates,
    # see https://www.keycloak.org/server/configuration.
    command: start-dev
    volumes:
      - ./libs/keycloak-themes/theme:/opt/keycloak/themes
  resource-server:
    image: keycloak-poc/resource-server:1.0
    ports:
      - '${RESOURCE_SERVER_PORT}:80'
    env_file: .env
  client-backend:
    image: keycloak-poc/keycloak-client-backend:1.0
    ports:
      - '${CLIENT_BACKEND_PORT}:80'
    env_file: .env
    depends_on:
      - keycloak
  client:
    image: node:16.16.0
    ports:
      - '${CLIENT_PORT}:8080'
    env_file: .env
    volumes:
      - ./client/src/:/home/node
    depends_on:
      - client-backend
